services:
  cap-web:
    container_name: cap-web
    image: ghcr.io/capsoftware/cap-web:latest
    restart: unless-stopped
    profiles: ["apps", "all"]    
    networks:
      - trf_ext
    environment:
      - DATABASE_URL=$CAP_DATABASE_URL
      - WEB_URL=https://cap.$DOMAINNAME_MR
      - NEXTAUTH_URL=https://cap.$DOMAINNAME_MR
      # CHANGE THESE TO YOUR OWN VALUES
      - DATABASE_ENCRYPTION_KEY=$CAP_DATABASE_ENCRYPTION_KEY
      - NEXTAUTH_SECRET=$CAP_NEXTAUTH_SECRET
      # CHANGE THESE TO MATCH YOUR MINIO or S3 STORAGE SETUP
      - CAP_AWS_ACCESS_KEY=$CAP_AWS_ACCESS_KEY
      - CAP_AWS_SECRET_KEY=$CAP_AWS_SECRET_KEY
      - CAP_AWS_BUCKET=capso
      - CAP_AWS_REGION=us-east-1
      - S3_PUBLIC_ENDPOINT=https://s3.$DOMAINNAME_HL
      - S3_INTERNAL_ENDPOINT=http://10.2.120.10:9000
    labels:
      - "traefik.enable=true"
      - "traefik.group=external"
      - "traefik.http.routers.cap-web-rtr.entrypoints=websecure"
      - "traefik.http.routers.cap-web-rtr.rule=Host(`cap.$DOMAINNAME_MR`)"
      - "traefik.http.routers.cap-web-rtr.service=cap-web-svc"
      - "traefik.http.services.cap-web-svc.loadbalancer.server.port=3000"
      - "traefik.docker.network=trf_ext"
      # External DNS
      - 'external-dns:homelab=[{ "type": "CNAME", "name": "cap.$DOMAINNAME_MR", "target": "external.$DOMAINNAME_MR", "proxy": true }]'      