services:
  cloudflared-mr:
    image: docker.io/cloudflare/cloudflared:2025.10.0@sha256:396cd2e6f021275ad09969a1b4f1a7e62ca5349fde62781ce082bb2c18105c70
    container_name: cloudflared-mr
    restart: no
    security_opt:
      - no-new-privileges:true
    profiles: ["core", "all"]
    networks:
      - trf_ext
    environment:
      - NO_AUTOUPDATE=true
      - TUNNEL_METRICS=0.0.0.0:8080
      - TUNNEL_ORIGIN_ENABLE_HTTP2=true
      - TUNNEL_POST_QUANTUM=true
      - TUNNEL_TRANSPORT_PROTOCOL=quic
      - DOMAINNAME_MR
      - CLOUDFLARE_MR_TUNNEL_ID
    command: tunnel -config /etc/cloudflared/config.yaml run
    volumes:
      - $DOCKERDIR/appdata/cloudflared/mr:/etc/cloudflared
    ports:
      - 8080:8080 # For metrics, optional

  cloudflared-hl:
    image: docker.io/cloudflare/cloudflared:2025.10.0@sha256:396cd2e6f021275ad09969a1b4f1a7e62ca5349fde62781ce082bb2c18105c70
    container_name: cloudflared-hl
    restart: no
    security_opt:
      - no-new-privileges:true
    profiles: ["core", "all"]
    networks:
      - trf_ext
    environment:
      - NO_AUTOUPDATE=true
      - TUNNEL_METRICS=0.0.0.0:8080
      - TUNNEL_ORIGIN_ENABLE_HTTP2=true
      - TUNNEL_POST_QUANTUM=true
      - TUNNEL_TRANSPORT_PROTOCOL=quic
      - DOMAINNAME_HL
      - CLOUDFLARE_HL_TUNNEL_ID
    command: tunnel -config /etc/cloudflared/config.yaml run
    volumes:
      - $DOCKERDIR/appdata/cloudflared/hl:/etc/cloudflared
    ports:
      - 8080:8080 # For metrics, optional