# Ghost - Blogging Platform
# Follow these steps on the host:
# sudo mkdir $DOCKERDIR/appdata/ghost
# sudo chown -R 1000:1000 $DOCKERDIR/appdata/ghost/

services:
  ghost:
    image: ghcr.io/astrateam-net/ghost
    tag: 5.123.0@sha256:6d7ae4b4a52f3e33f14f5c88792a2f723c9392034550dd28804f7b61a9d2b963
    container_name: ghost
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Moscow
      - url=https://$DOMAINNAME_MR
      - NODE_ENV=development
      - admin__url=https://blog-admin.$DOMAINNAME_MR
      - database__client=mysql
      - database__connection__host=
      - database__connection__user=ghost
      - database__connection__password=ghost
      - database__connection__database=ghost
      - database__connection__port=3306
      - database__connection__ssl=false
      - database__connection__pool=true
      - database__connection__max=10
    ports:
      - 2368:2368
    volumes:
      - $DOCKERDIR/appdata/ghost:/var/lib/ghost/content