services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - trf_int 
    ports:
     - "2424:22"
    volumes:
      - $DOCKERDIR/appdata/gitlab/data:/var/opt/gitlab
      - $DOCKERDIR/appdata/gitlab/logs:/var/log/gitlab
      - $DOCKERDIR/appdata/gitlab/config:/etc/gitlab
    shm_size: '256m'  
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      # HTTP Routers
      - "traefik.http.routers.gitlab-rtr.entrypoints=websecure"
      - "traefik.http.routers.gitlab-rtr.rule=Host(`gitlab.$DOMAINNAME_HL`)"
      # HTTP Services
      - "traefik.http.routers.gitlab-rtr.service=gitlab-svc"
      - "traefik.http.services.gitlab-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=trf_int"

