services:
  gitlab:
    image: gitlab/gitlab-ce:18.4.1-ce.0@sha256:d24a77b3743174e055646c523b65862587e4fd44ed8aec8fa8a7dd2321299ebd
    container_name: gitlab
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - trf_int 
    # ports:
    #  - "2424:22"
    volumes:
      - $DOCKERDIR/appdata/gitlab/data:/var/opt/gitlab
      - $DOCKERDIR/appdata/gitlab/logs:/var/log/gitlab
      - $DOCKERDIR/appdata/gitlab/config:/etc/gitlab
      - /mnt/synology-gitlab-backups:/mnt/backups
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['backup_upload_connection'] = {
          :provider => 'Local',
          :local_root => '/mnt/backups'
        }
        gitlab_rails['backup_upload_remote_directory'] = 'gitlab_backups'  
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      # HTTP Routers
      - "traefik.http.routers.gitlab-rtr.entrypoints=websecure"
      - "traefik.http.routers.gitlab-rtr.rule=Host(`gitlab.$DOMAINNAME_HL`)"
      # HTTP Services
      - "traefik.http.routers.gitlab-rtr.service=gitlab-svc"
      - "traefik.http.services.gitlab-svc.loadbalancer.server.port=80"
      # TCP Router for SSH
      - "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc"
      - "traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=22"
      - "traefik.docker.network=trf_int"

