# Matomo - Web Analytics
# Follow these steps on the host:
# sudo mkdir $DOCKERDIR/appdata/matomo
# sudo mkdir $DOCKERDIR/appdata/matomo/config
# sudo mkdir $DOCKERDIR/appdata/matomo/misc
# sudo mkdir $DOCKERDIR/appdata/matomo/tmp
# sudo mkdir $DOCKERDIR/appdata/matomo/lang
# sudo chown -R www-data:www-data $DOCKERDIR/appdata/matomo/
# sudo chown -R www-data:www-data $DOCKERDIR/appdata/matomo/

services:
  matomo:
    image: matomo@sha256:bced7f6b05425cbf2bc26fd0226e0e84a530e7671dc6e293284670040b1c59da
    container_name: matomo
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]    
    networks:
      - trf_int
    # environment:
    #   - MATOMO_DB_HOST=$MARIADB_HOST
    #   - MATOMO_DB_USER=$MATOMO_DB_USER
    #   - MATOMO_DB_PASSWORD_FILE=/run/secrets/mariadb_matomo_password
    #   - MATOMO_DB_NAME=$MATOMO_DB_NAME
    #   - MATOMO_DB_PREFIX=matomo_
    #   - MATOMO_DB_PORT=$MARIADB_PORT
    #   - MATOMO_DB_TABLE_PREFIX=matomo_
    #   - MARIADB_AUTO_UPGRADE=1
    # secrets:
    #   - mariadb_matomo_password
    volumes:
      - /etc/hosts:/etc/hosts
      - $DOCKERDIR/appdata/matomo/config:/var/www/html/config
      - $DOCKERDIR/appdata/matomo/misc:/var/www/html/misc
      - $DOCKERDIR/appdata/matomo/tmp:/var/www/html/tmp
      - $DOCKERDIR/appdata/matomo/lang:/var/www/html/lang
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      - "traefik.http.routers.matomo-int-rtr.entrypoints=websecure"
      - "traefik.http.routers.matomo-int-rtr.rule=Host(`matomo.$DOMAINNAME_HL`)"
      - "traefik.http.routers.matomo-int-rtr.service=matomo-svc"
      - "traefik.http.services.matomo-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=trf_int"
      #- "traefik.http.routers.matomo-int-rtr.tls.certresolver=zerossl"

