services:
  obsidian:
    image: linuxserver/obsidian:1.9.10
    container_name: obsidian
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    profiles: ["apps", "all"]
    networks:
      - trf_int
    volumes:
      - $DOCKERDIR/appdata/obsidian/config:/config:rw
      # - $DOCKERDIR/appdata/obsidian/data:/data
    environment: 
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=iputils-ping|net-tools|curl|wget|vim|dnsutils
    shm_size: "5gb"
    # devices:
    #   - /dev/dri:/dev/dri #optional
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      # HTTP Routers
      - "traefik.http.routers.obsidian-rtr.entrypoints=websecure"
      - "traefik.http.routers.obsidian-rtr.rule=Host(`notes.$DOMAINNAME_HL`)"
      #- "traefik.http.routers.portainer-rtr.tls.certresolver=zerossl"
      # Middlewares
      #- "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.obsidian-rtr.service=obsidian-svc"
      - "traefik.http.services.obsidian-svc.loadbalancer.server.port=3000"
      - "traefik.docker.network=trf_int"      