services:
  obsidian:
    image: linuxserver/obsidian:1.9.10
    container_name: obsidian
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - trf_int
    volumes:
      - $DOCKERDIR/appdata/obsidian/config:/config
    environment: 
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      # HTTP Routers
      - "traefik.http.routers.obsidian-rtr.entrypoints=websecure"
      - "traefik.http.routers.obsidian-rtr.rule=Host(`notes.$DOMAINNAME_HL`)"
      #- "traefik.http.routers.portainer-rtr.tls.certresolver=zerossl"
      # Middlewares
      #- "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.obsidian-rtr.service=obsidian-svc"
      - "traefik.http.services.obsidian-rtr.loadbalancer.server.port=3001"
      - "traefik.docker.network=trf_int"      