services:
  paperless:
    # image: ghcr.io/astrateam-net/paperless-ngx:2.18.4
    image: paperless-dev:latest
    container_name: paperless
    profiles: ["apps", "all"]
    networks:
      - trf_int
      - paperless_internal
    restart: unless-stopped
    depends_on:
      - gotenberg
      - tika
    # ports:
    #   - "8000:8000"
    volumes:
      - $DOCKERDIR/appdata/paperless/data:/usr/src/paperless/data
      - $DOCKERDIR/appdata/paperless/media:/usr/src/paperless/media
      - $DOCKERDIR/appdata/paperless/export:/usr/src/paperless/export
      # Direct NFS subpath mounts
      - type: volume
        source: paperless-docs-root
        target: /usr/src/paperless/media/documents/originals/docs
      - type: volume
        source: paperless-consume-folder
        target: /usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: $PPR_REDIS_URL
      PAPERLESS_REDIS_PREFIX: PPR

      PAPERLESS_DBHOST: $PPR_DB_POSTGRESDB_HOST
      PAPERLESS_DBPORT: $PPR_DB_POSTGRESDB_PORT
      # PAPERLESS_DBNAME: $PPR_DB_POSTGRESDB_DATABASE
      # PAPERLESS_DBUSER: $PPR_DB_POSTGRESDB_USER
      # PAPERLESS_DBPASSWORD: $PPR_DB_POSTGRESDB_PASSWORD
      PAPERLESS_DBENGINE: mariadb
      # PAPERLESS_DBSSLMODE: disable
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
      PAPERLESS_MEDIA_ROOT: /usr/src/paperless/media
      PAPERLESS_FILENAME_FORMAT: /docs/98_Unprocessed/{{ title }}

      PAPERLESS_TIME_ZONE: Europe/Moscow
      PAPERLESS_URL: https://dms.$DOMAINNAME_HL
      PAPERLESS_OCR_LANGUAGE: rus 
      PAPERLESS_OCR_LANGUAGES: rus
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_CONSUMER_POLLING: 5
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      
      PAPERLESS_SOCIAL_AUTO_SIGNUP: "false"
      PAPERLESS_DISABLE_REGULAR_LOGIN: "false"
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: "false"
      # PAPERLESS_SECRET_KEY: $PPR_SECRET_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      - "traefik.http.routers.paperless-int-rtr.entrypoints=websecure"
      - "traefik.http.routers.paperless-int-rtr.rule=Host(`dms.$DOMAINNAME_HL`)"
      - "traefik.http.routers.paperless-int-rtr.service=paperless-svc"
      - "traefik.http.services.paperless-svc.loadbalancer.server.port=8000"
      - "traefik.docker.network=trf_int"
  gotenberg:
    image: ghcr.io/astrateam-net/gotenberg:8.21.1
    restart: unless-stopped
    networks:
      - paperless_internal
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: ghcr.io/paperless-ngx/tika:2.9.1-full
    restart: unless-stopped
    networks:
      - paperless_internal

volumes:
  paperless-docs-root:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.2.120.10,rw,soft,intr,vers=4
      device: ":/volume1/01_Documents"
  paperless-consume-folder:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.2.120.10,rw,soft,intr,vers=4
      device: ":/volume1/01_Documents/98_Upload"