services:
  # phpMyAdmin - Database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - trf_int
    environment:
      - PMA_HOST=$MARIADB_HOST
      - PMA_PORT=$MARIADB_PORT
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_admin_password
    secrets:
      - mariadb_admin_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.phpmyadmin-int-rtr.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin-int-rtr.rule=Host(`pma.$DOMAINNAME_HL`)"
      - "traefik.http.routers.phpmyadmin-int-rtr.tls.certresolver=zerossl"
      # Middlewares
      #- "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.phpmyadmin-int-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=trf_int"