services:
  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    restart: unless-stopped
    profiles: ["apps", "all"]      
    network_mode: host
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents    
    ports:
      - 5665:5665
    volumes:
      - $DOCKERDIR/appdata/torrserver/CACHE:/opt/ts/torrents
      - $DOCKERDIR/appdata/torrserver/CONFIG:/opt/ts/config