services:
  # WhoAmI - For Testing and Troubleshooting
  whoami-ext:
    image: traefik/whoami@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: whoami-ext
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - trf_ext
    labels:
      - "traefik.enable=true"
      - "traefik.group=external"
      # HTTP Routers
      - "traefik.http.routers.whoami-ext-rtr.entrypoints=websecure"
      - "traefik.http.routers.whoami-ext-rtr.rule=Host(`whoami-ext.$DOMAINNAME_HL`)"
      - "traefik.http.routers.whoami-ext-rtr.tls.certresolver=dns-cloudflare"
      # Middlewares
      #- "traefik.http.routers.whoami-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.whoami-ext-rtr.service=whoami-ext-svc"
      - "traefik.http.services.whoami-ext-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=trf_ext"

  whoami-int:
    image: traefik/whoami@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: whoami-int
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - trf_int
    labels:
      - "traefik.enable=true"
      - "traefik.group=internal"
      # HTTP Routers
      - "traefik.http.routers.whoami-int-rtr.entrypoints=websecure"
      - "traefik.http.routers.whoami-int-rtr.rule=Host(`whoami-int.$DOMAINNAME_HL`)"
      #- "traefik.http.routers.whoami-int-rtr.tls.certresolver=zerossl"
      # Middlewares
      #- "traefik.http.routers.whoami-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.whoami-int-rtr.service=whoami-int-svc"
      - "traefik.http.services.whoami-int-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=trf_int"