########################### THIS COMPOSE FILE
# - Synology (ivn-nas1) - Synology DS1821+
# - Prefix/suffix "ivn-nas1" refers to the above host
# - Docker version 24.0.2, build 610b8d0
# - Docker Compose version v2.20.1-6047-g6817716

########################### NETWORKS
networks:
  default:
    driver: bridge

# Docker Compose v2.20 or greater required to use "include"
include:
  ########################### SERVICES
  # PREFIX ivns-nas1 = Synology DS1821+ NAS
  # HOSTNAME=ivn-nas1 - defined in .env
  - compose/$HOSTNAME/minio.yml
  - compose/$HOSTNAME/onepassword.yml
