
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

  trf_ext:
    name: trf_ext
    driver: ipvlan
    driver_opts:
      parent: eth0.1125
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.2.125.0/24
          gateway: 10.2.125.1
          ip_range: 10.2.125.224/27

  trf_int:
    name: trf_int
    driver: ipvlan
    driver_opts:
      parent: eth0.1130
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.2.130.0/24
          gateway: 10.2.130.1
          ip_range: 10.2.130.224/27

########################### SECRETS
secrets:
  # basic_auth_credentials:
  #   file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  # traefik_forward_auth:
  #   file: $DOCKERDIR/secrets/traefik_forward_auth
  mariadb_admin_password:
    file: $DOCKERDIR/secrets/mariadb_admin_password
  mariadb_matomo_password:
    file: $DOCKERDIR/secrets/mariadb_matomo_password
  pgadmin_default_password:
    file: $DOCKERDIR/secrets/pgadmin_default_password
  # authelia_jwt_secret:
  #   file: $DOCKERDIR/secrets/authelia_jwt_secret
  # authelia_session_secret:
  #   file: $DOCKERDIR/secrets/authelia_session_secret
  # authelia_storage_mysql_password:
  #   file: $DOCKERDIR/secrets/authelia_storage_mysql_password
  # authelia_notifier_smtp_password:
  #   file: $DOCKERDIR/secrets/authelia_notifier_smtp_password
  # authelia_duo_api_secret_key:
  #   file: $DOCKERDIR/secrets/authelia_duo_api_secret_key
  # authelia_storage_encryption_key:
  #   file: $DOCKERDIR/secrets/authelia_storage_encryption_key
  # guac_db_name:
  #   file: $DOCKERDIR/secrets/guac_db_name
  # guac_mysql_user:
  #   file: $DOCKERDIR/secrets/guac_mysql_user
  # guac_mysql_password:
  #   file: $DOCKERDIR/secrets/guac_mysql_password

include:
  ########################### SERVICES
  # PREFIX hs = Home Server
  # HOSTNAME=hs - defined in .env

  # CORE
  - compose/$HOSTNAME/traefik-ext.yaml
  - compose/$HOSTNAME/traefik-int.yaml
  - compose/$HOSTNAME/socket-proxy.yaml
  - compose/$HOSTNAME/cloudflared-mr.yaml
  - compose/$HOSTNAME/external-dns.yaml
  # - compose/$HOSTNAME/oauth.yml
  # - compose/$HOSTNAME/authelia.yml
  - compose/$HOSTNAME/portainer.yaml
  # - compose/$HOSTNAME/dockge.yml
  # SECURITY
  # - compose/$HOSTNAME/crowdsec.yml
  # - compose/$HOSTNAME/traefik-bouncer.yml
  # FRONTEND
  # - compose/$HOSTNAME/autoindex.yml
  # - compose/$HOSTNAME/homepage.yml
  - compose/$HOSTNAME/phpmyadmin.yaml
  - compose/$HOSTNAME/pgadmin.yaml
  # - compose/$HOSTNAME/sitespeed.yml
  - compose/$HOSTNAME/whoami.yaml
  # DOWNLOADERS
  # - compose/$HOSTNAME/jdownloader.yml
  # - compose/$HOSTNAME/qbittorrent.yml
  # - compose/$HOSTNAME/sabnzbd.yml
  # PVRS
  # - compose/$HOSTNAME/sonarr.yml
  # - compose/$HOSTNAME/radarr.yml
  # - compose/$HOSTNAME/lidarr.yml
  # COMPLEMENTARY APPS
  # - compose/$HOSTNAME/prowlarr.yml
  # - compose/$HOSTNAME/notifiarr.yml
  # - compose/$HOSTNAME/bazarr.yml
  # - compose/$HOSTNAME/picard.yml
  # MONITORING
  - compose/$HOSTNAME/matomo.yaml
  # - compose/$HOSTNAME/grafana.yml
  # - compose/$HOSTNAME/uptime-kuma.yml
  # - compose/$HOSTNAME/dozzle.yml
  # - compose/$HOSTNAME/scrutiny.yml
  # - compose/$HOSTNAME/radarr-exporter.yml
  # - compose/$HOSTNAME/sonarr-exporter.yml
  # - compose/$HOSTNAME/lidarr-exporter.yml
  # - compose/$HOSTNAME/prowlarr-exporter.yml
  # - compose/$HOSTNAME/sabnzbd-exporter.yml
  # - compose/$HOSTNAME/node-exporter.yml
  # # ADMIN
  # - compose/$HOSTNAME/guacamole.yml
  # # - compose/$HOSTNAME/kasm.yml
  # - compose/$HOSTNAME/it-tools.yml
  # # UTILITIES
  # - compose/$HOSTNAME/firefox.yml
  # - compose/$HOSTNAME/firefly.yml
  # # FILE MANAGEMENT
  # - compose/$HOSTNAME/vscode.yml
  # - compose/$HOSTNAME/makemkv.yml
  # - compose/$HOSTNAME/mkvtoolnix.yml
  # # NETWORK
  # - compose/$HOSTNAME/gluetun.yml
  # # MAINTENANCE
  - compose/$HOSTNAME/docker-gc.yaml
  # - compose/$HOSTNAME/deunhealth.yml
  # # Blog
  - compose/$HOSTNAME/ghost.yaml