########################### THIS COMPOSE FILE
# - Synology (mrk-nas01) - Synology DS220
# - Prefix/suffix "mrk-nas01" refers to the above host
# - Docker version 20.10.23, build 876964a
# - Docker Compose version v2.23.3

########################### NETWORKS
########################### NETWORKS
########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

########################### SECRETS
# secrets:
#   basic_auth_credentials:
#     file: ${SECRETSDIR}/basic_auth_credentials
#   stepca_init_password:
#     file: ${SECRETSDIR}/stepca_init_password

# Docker Compose v2.20 or greater required to use "include"
include:
  ########################### SERVICES
  # PREFIX mrk-nas01 = Synology DS221+ NAS
  # HOSTNAME=mrk-nas01 - defined in .env
  - compose/$HOSTNAME/minio.yml
  - compose/$HOSTNAME/onepassword.yml