########################### THIS COMPOSE FILE
# - Synology (mrk-nas01) - Synology DS220
# - Prefix/suffix "mrk-nas01" refers to the above host
# - Docker version 28.3.3, build 980b856
# - Docker Compose version v2.39.1

########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  trf_proxy:
    name: trf_proxy
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 10.1.140.0/24
          gateway: 10.1.140.1
          ip_range: 10.1.140.224/27

########################### SECRETS
secrets:
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
#   basic_auth_credentials:
#     file: ${SECRETSDIR}/basic_auth_credentials
#   stepca_init_password:
#     file: ${SECRETSDIR}/stepca_init_password

# Docker Compose v2.20 or greater required to use "include"
include:
  ########################### SERVICES
  # PREFIX mrk-nas01 = Synology DS221+ NAS
  # HOSTNAME=mrk-nas01 - defined in .env

  # CORE
  - compose/${HOSTNAME}/traefik.yaml
  - compose/${HOSTNAME}/socket-proxy.yaml
  # - compose/$HOSTNAME/oauth.yml
  - compose/$HOSTNAME/portainer.yaml