http:
  #Routers
  routers:

    ##WIKI
    oldwiki-rtr:
      rule: "Host(`oldwiki.{{env "DOMAIN1"}}.net`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: oldwiki
      tls:
        certResolver: internalca
        options: tls-opts@file

    ##JIRA
    oldjira-rtr:
      rule: "Host(`oldjira.{{env "DOMAIN1"}}.net`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: oldwiki
      tls:
        certResolver: internalca
        options: tls-opts@file
          
  #Services
  services:
    ##WIKI
    oldwiki:
      loadBalancer:
        passHostHeader: true
        serversTransport: oldwiki
        servers:
          - url: "http://10.10.0.124:8090"
    ##JIRA
    oldjira:
      loadBalancer:
        passHostHeader: true
        serversTransport: oldjira
        servers:
          - url: "http://10.10.0.141:8080"

  serversTransports:
    oldwiki:
      insecureSkipVerify: false
    oldjira:
      insecureSkipVerify: false