http:
  #Routers
  routers:

    ##NODE01
    pve01-rtr:
      rule: "Host(`oldwiki.{{env "DOMAIN1"}}.net`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: oldwiki
      tls:
        certResolver: internalca
        options: tls-opts@file

          
  #Services
  services:
    ##NODE01
    pve01-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: pve01
        servers:
          - url: "https://10.10.0.149:8090"

  serversTransports:
    oldwiki:
      insecureSkipVerify: true
