http:
  #Routers
  routers:
    ##NODE01
    pve01-rtr:
      rule: "Host(`pve01.{{env "DOMAIN1"}}.net`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: pve01-svc
      tls:
        certResolver: internalca
        options: tls-opts@file
    ##NODE02
    pve02-rtr:
      rule: "Host(`pve02.{{env "DOMAIN1"}}.net`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: pve02-svc
      tls:
        certResolver: internalca
        options: tls-opts@file    

  #Services
  services:
    ##NODE01
    pve01-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: pve01
        servers:
          - url: "https://{{env "VLAN_1110"}}.11:8006"
    ##NODE02
    pve02-svc:
      loadBalancer:
        passHostHeader: true
        # serversTransport: pve02
        servers:
          - url: "https://{{env "VLAN_1110"}}.12:8006"      

  serversTransports:
    pve01:
      insecureSkipVerify: true