# OnePassword Pod for Podman play kube
#
# This manifest is designed for use with 1Password CLI (`op run --env-file .env -- podman play kube ...`)
# All secrets and env vars should be provided via the environment at runtime, e.g. using op:// references in your .env file.
#
# Note: Podman does NOT support Service objects. To publish ports to the host, use hostPort in the Pod spec.
---
apiVersion: v1
kind: Pod
metadata:
  name: onepassword-pod
  labels:
    app: onepassword
spec:
  containers:
    - name: onepassword-connect-api
      image: docker.io/1password/connect-api:1.7.3
      ports:
        - containerPort: 8080
          hostPort: 30080
      env:
        - name: PUID
          value: "${PUID}"
        - name: PGID
          value: "${PGID}"
        - name: OP_SESSION
          value: "${OP_SESSION}"
        - name: XDG_DATA_HOME
          value: "/config"
      volumeMounts:
        - name: config
          mountPath: /config
      securityContext:
        allowPrivilegeEscalation: false
    - name: onepassword-connect-sync
      image: docker.io/1password/connect-sync:1.7.3
      ports:
        - containerPort: 8443
          hostPort: 30443
      env:
        - name: PUID
          value: "${PUID}"
        - name: PGID
          value: "${PGID}"
        - name: OP_SESSION
          value: "${OP_SESSION}"
        - name: XDG_DATA_HOME
          value: "/config"
      volumeMounts:
        - name: config
          mountPath: /config
      securityContext:
        allowPrivilegeEscalation: false
  volumes:
    - name: config
      emptyDir:
        medium: Memory # tmpfs (memory-backed)