http:
  middlewares:
    obsidiansync-cors:  # Your CORS middleware with recommended additions
      headers:
        accessControlAllowMethods:
          - GET
          - PUT
          - POST
          - HEAD
          - DELETE
          - OPTIONS  # Added for preflight requests
          - COPY    # Added for full CouchDB support (optional but useful)
        accessControlAllowHeaders:
          - accept
          - authorization
          - content-type
          - origin
          - referer
          - x-csrf-token  # Added for CouchDB CSRF (optional)
        accessControlAllowOriginList:
          - app://obsidian.md
          - capacitor://localhost
          - http://localhost
          - https://obsidian-livesync.{{env "DOMAINNAME_MR"}}
        accessControlMaxAge: 3600
        addVaryHeader: true
        accessControlAllowCredentials: true