---
originRequest:
  originServerName: external.${DOMAINNAME_MR}
  
ingress:
  - hostname: ${DOMAINNAME_HL}
    service: https://traefik
  - hostname: "*.${DOMAINNAME_HL}"
    service: https://traefik
  - service: http_status:404
