---
tunnel: $CLOUDFLARE_MR_TUNNEL_ID
credentials-file: /etc/cloudflared/cloudflare-tunnel.json
originRequest:
  originServerName: external.${DOMAINNAME_MR}
  
ingress:
  - hostname: ${DOMAINNAME_MR}
    service: https://traefik-external:443
  - hostname: "*.${DOMAINNAME_MR}"
    service: https://traefik-external:443
  - service: http_status:404
