services:
  # Minio 
  minio-local:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio-local
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DOCKERDIR}/appdata/minio-local/config:/app/data
      - /volume1/Minio:/data  
    command: server /data --console-address ":8890"  
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://minio.${DOMAIN1}.net
      # MINIO_DOMAIN: s3.${DOMAIN1}.net
      MINIO_SERVER_URL: https://s3.${DOMAIN1}.net

  minio-console:
    image: ghcr.io/huncrys/minio-console:v1.8.1@sha256:c4b0be15c6fd1aacb0fed9f93a5390bf360c409d3a3b1929636cf357dbd3570a
    container_name: minio-console
    restart: unless-stopped
    network_mode: host
    command: console server
    environment:
      CONSOLE_MINIO_SERVER: http://10.1.120.25:9000