services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.${DOMAIN1}.net
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
      - DOCKER_SOCKET=tcp://socket-proxy:2375
    networks:
      docker_harbor:
        ipv4_address: 172.20.0.11
      socket_proxy: {}

networks:
  docker_harbor:
    external: true