services:
  # OnePassword Connect API
  onepassword-connect-api:
    image: docker.io/1password/connect-api:1.8.1@sha256:8fe7bcd50c9e73899e0a1aa5aa43421ca75fbceacb33dd07f6418c4116e637a1
    container_name: onepassword-connect-api
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      OP_SESSION: ${OP_SESSION}
      OP_HTTP_PORT: 7080
      XDG_DATA_HOME: /config

  # OnePassword Connect Sync
  onepassword-connect-sync:
    image: docker.io/1password/connect-sync:1.7.4@sha256:27e7ec47e1ad8eaa2f54764fa0736954a5119d0155dea3c923c481c89c5f964c
    container_name: onepassword-connect-sync
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      OP_SESSION: ${OP_SESSION}
      OP_HTTP_PORT: 7081
      XDG_DATA_HOME: /config    
volumes:
  data:
    driver: local
    driver_opts:
      device: tmpfs
      o: uid=999,gid=999
      type: tmpfs      