services:
  # Smallstep CA - private certificate authority
  step-ca:
    image: smallstep/step-ca
    container_name: step-ca
    # security_opt:
    #   - no-new-privileges:true
    # restart: unless-stopped  # Need be to disabled when running `step ca init` 
    networks:
      bond0.1140:
        ipv4_address: ${VLAN_1140}.245
    # ports:
    #   - "9000:9000"
    volumes:
    # We must firs define special permission `sudo chmod -R 700 step-ca` `sudo chown -R 1000:1000 step-ca`
      - ${DOCKERDIR}/appdata/step-ca:/home/step 
    environment:
      DOCKER_STEPCA_INIT_NAME: AT ACME Enterprise CA
      DOCKER_STEPCA_INIT_DNS_NAMES: "acme.${DOMAIN1}.net,${VLAN_1140}.245" 
      DOCKER_STEPCA_INIT_ACME:
      DOCKER_STEPCA_INIT_PROVISIONER_NAME: ${DOCKER_STEPCA_INIT_PROVISIONER_NAME}
      DOCKER_STEPCA_INIT_PASSWORD_FILE: /run/secrets/stepca_init_password
    secrets:
      - stepca_init_password
    # command: step ca provisioner add acme --type ACME  # This runs the step ca init command when the container starts , after first init must be disabled