services:
  # Uptime Kuma
  uptime-kuma-local:
    image: ghcr.io/louislam/uptime-kuma:2.0.0-beta.1@sha256:37cefd560df5c39222e34a487389fe3d38bd767ce6e3cf06da0b64e288f552c6
    container_name: uptime-kuma-local
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      bond0.1140:
        ipv4_address: ${VLAN_1140}.252
    # ports:
    #   - "3001:3001"
    volumes:
      - ${DOCKERDIR}/appdata/uptime-kuma-local:/app/data
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UPTIME_KUMA_DB_TYPE: mariadb
      UPTIME_KUMA_DB_HOSTNAME: mysql
      UPTIME_KUMA_DB_PORT: 3306
      UPTIME_KUMA_DB_NAME: uptime
      UPTIME_KUMA_DB_USERNAME: ${UPTIME_KUMA_DB_USERNAME}
      UPTIME_KUMA_DB_PASSWORD: ${UPTIME_KUMA_DB_PASSWORD}
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.uptime-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptime-rtr.rule=Host(`uptime.${DOMAIN1}.net`) || Host(`status.${DOMAIN1}.net`)"
      # - "traefik.http.routers.uptime-rtr.tls=true"
      # Middlewares
      # - "traefik.http.routers.uptime-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.uptime-rtr.service=uptime-svc"
      - "traefik.http.services.uptime-svc.loadbalancer.server.port=3001"