---
originRequest:
  originServerName: external.${DOMAINNAME_HL}

ingress:
  - hostname: ${DOMAINNAME_HL}
    service: https://traefik-ext
  - hostname: "*.${DOMAINNAME_HL}"
    service: https://traefik-ext
  - service: http_status:404
