---
tunnel: $CLOUDFLARE_HL_TUNNEL_ID
credentialsFile: /etc/cloudflared/cloudflare-tunnel.json

originRequest:
  originServerName: external.${DOMAINNAME_HL}

ingress:
  - hostname: ${DOMAINNAME_HL}
    service: https://traefik-ext
  - hostname: "*.${DOMAINNAME_HL}"
    service: https://traefik-ext
  - service: http_status:404
