services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true   
    group_add:
      - 937 
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: ${TZ}
    volumes:
      - ${DOCKERDIR}/appdata/jellyfin/config:/config:rw
      - ${DOCKERDIR}/appdata/jellyfin/cache:/cache:rw
      - ${DOCKERDIR}/appdata/jellyfin/logs:/logs:rw
      - /volume1/Media/Movies:/media:rw
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0