services:
  # Minio 
  minio-s3:
    image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio-s3
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    volumes:
      # - ${DOCKERDIR}/appdata/minio-local/config:/app/data
      - /volume1/s3data:/data  
    command: server /data --console-address ":8890"  
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://minio.${DOMAIN1}.am
      # MINIO_DOMAIN: s3.${DOMAIN1}.am
      MINIO_SERVER_URL: https://s3.${DOMAIN1}.am
      # ## ENTRA ID
      # MINIO_IDENTITY_OPENID_CONFIG_URL: "https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0/.well-known/openid-configuration"
      # MINIO_IDENTITY_OPENID_CLIENT_ID: ${MINIO_ENTRA_CLIENT_ID}
      # MINIO_IDENTITY_OPENID_CLIENT_SECRET: ${MINIO_ENTRA_SECRET_ID}
      # MINIO_IDENTITY_OPENID_SCOPES: "profile openid email"
      # MINIO_IDENTITY_OPENID_CLAIM_NAME: "groups"
      # MINIO_IDENTITY_OPENID_REDIRECT_URI: "https://minio.${DOMAIN1}.net/oauth_callback"
      # MINIO_IDENTITY_OPENID_DISPLAY_NAME: "EntraID"
      # MINIO_IDENTITY_OPENID_COMMENT: "EntraID"

  minio-console:
    image: ghcr.io/huncrys/minio-console:v1.8.1
    container_name: minio-console
    restart: unless-stopped
    network_mode: host
    command: console server
    environment:
      CONSOLE_MINIO_SERVER: http://10.2.120.10:9000