services:
  # OnePassword Connect API
  onepassword-connect-api:
    image: docker.io/1password/connect-api:1.7.4@sha256:f97189814239381e6dd88577f2b0b838a64e006a460608455b3127c15b174601
    container_name: onepassword-connect-api
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - "8080:8080"      
    volumes:
      - data:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      OP_SESSION: ${OP_SESSION}
      OP_HTTP_PORT: 7080
      XDG_DATA_HOME: /config

  # OnePassword Connect Sync
  onepassword-connect-sync:
    image: docker.io/1password/connect-sync:1.8.1@sha256:d5e937b2b7e314dbbaffacf469dc8f30376b5954a3ad836c8d96e6cb579d7fab
    container_name: onepassword-connect-sync
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - "8443:8443"      
    volumes:
      - data:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      OP_SESSION: ${OP_SESSION}
      OP_HTTP_PORT: 7081
      XDG_DATA_HOME: /config    
volumes:
  data:
    driver: local
    driver_opts:
      device: tmpfs
      o: uid=999,gid=999
      type: tmpfs      